package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, QUIT, JOB_EXECUTION, JOB_RESULT,
	ASK_JOB_RESULT, JOB_FRACTALID_RESULT, ASK_JOB_FRACTALID_RESULT, STOP_JOB, ASK_STATUS, TELL_STATUS,
	IDLE
}
